name = "cf-site-assets"
type = "webpack"
account_id = "1a281281e78d332d3a9c862b38fbf2bf"
zone_id = "029cc4b7a5c892f22bfd8e085132a639"
workers_dev = false
route = "https://cf-site-assets.deaddodgeydigitaldeals.com/*"


[site]
bucket = "./public"
